import type { JobApplication } from "./types";

export const defaultApplications: JobApplication[] = [
  {
    id: "app-1",
    company: "Nusa Data Labs",
    position: "Data Analyst Intern",
    status: "Accepted",
    applicationDate: "2026-04-18",
    salary: 6500000,
    nextAction: ["Decide", "Send email"],
    website: "https://nusadata.example",
    contact: "hr@nusadata.example",
  },
  {
    id: "app-2",
    company: "Arunika Studio",
    position: "Product Designer",
    status: "Rejected",
    applicationDate: "2026-04-21",
    salary: 7000000,
    nextAction: ["Follow up"],
    website: "https://arunika.example",
    contact: "talent@arunika.example",
  },
  {
    id: "app-3",
    company: "Orbit Fintech",
    position: "Frontend Engineer",
    status: "Interviewed",
    applicationDate: "2026-04-25",
    salary: 9500000,
    nextAction: ["Prepare Interview", "Waiting"],
    website: "https://orbit.example",
    contact: "recruiting@orbit.example",
  },
  {
    id: "app-4",
    company: "Sagara Works",
    position: "Business Analyst",
    status: "Applied",
    applicationDate: "2026-05-01",
    salary: 7500000,
    nextAction: ["Waiting"],
    website: "https://sagara.example",
    contact: "people@sagara.example",
  },
  {
    id: "app-5",
    company: "Kirana Cloud",
    position: "Backend Engineer",
    status: "Offer",
    applicationDate: "2026-05-04",
    salary: 11000000,
    nextAction: ["Decide", "Follow up"],
    website: "https://kirana.example",
    contact: "jobs@kirana.example",
  },
  {
    id: "app-6",
    company: "Lentera AI",
    position: "ML Operations Intern",
    status: "Interviewed",
    applicationDate: "2026-05-07",
    salary: 8000000,
    nextAction: ["Prepare Interview"],
    website: "https://lentera.example",
    contact: "careers@lentera.example",
  },
];
